spring.application.name=expense-management

spring.datasource.url=jdbc:postgresql://localhost:5432/expenseDB
spring.datasource.username=postgres
spring.datasource.password=bishal$980091

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

security.jwt.secret=Project_Expense_Management_Postgres_Java_Spring
security.jwt.expiration=86400000